### ISSUE TITLE
Watching for changes

### ISSUE THREAD

**Issue by moraleslevi** [nanobox-quickstarts/nanobox-adonis#1]
I am using adonisjs 4.0-dev and I'm having issues watching for file changes when running the application. When i use `adonis serve --dev` outside of nanobox it will watch for changes to my files and reload the application, but when running inside of nanobox none of my changes are detected and I have to manually restart this application. This is not an ideal workflow but I'm not sure how to fix it. I realize this likely only involves the yet to be officially release 4.0-dev version but wanted to put it out there as it look like 4.0 release is just around the corner.

**Comment by sanderson** [comment]
@moraleslevi Since files are mounted from your local disk into the virtual environment, Nanobox needs to pass the filesystem notifications up to the VM. This is disabled by default, but you can enable it in your `boxfile.yml`:

```yaml
run.config:
  #...
  fs_watch: true
```

Is file-watching pretty standard with Adonis development? If so, we can include the `fs_watch` setting in the quickstart boxfile.

**Comment by moraleslevi** [comment]
Thanks @sanderson that worked! To be honest I'm quite new to both Adonis and Nanobox (loving it so far by the way) so take my opinion with a grain of salt, but in my own personal use the file-watching has been pretty integral to my development process. I know the Adonis quick start documentation recommends using the `--dev` flag when serving the application which fires up the file watcher.

**Comment by sanderson** [comment]
Good enough for me. I'll add it in.
